<?php


/**
 * Base class that represents a query for the 'cgt_telemetryview' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jun 14 08:32:58 2016
 *
 * @method     CgtTelemetryQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     CgtTelemetryQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     CgtTelemetryQuery orderBySql($order = Criteria::ASC) Order by the sql column
 * @method     CgtTelemetryQuery orderByActive($order = Criteria::ASC) Order by the active column
 * @method     CgtTelemetryQuery orderByCreatedBy($order = Criteria::ASC) Order by the created_by column
 * @method     CgtTelemetryQuery orderByUpdatedBy($order = Criteria::ASC) Order by the updated_by column
 * @method     CgtTelemetryQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     CgtTelemetryQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 *
 * @method     CgtTelemetryQuery groupById() Group by the id column
 * @method     CgtTelemetryQuery groupByName() Group by the name column
 * @method     CgtTelemetryQuery groupBySql() Group by the sql column
 * @method     CgtTelemetryQuery groupByActive() Group by the active column
 * @method     CgtTelemetryQuery groupByCreatedBy() Group by the created_by column
 * @method     CgtTelemetryQuery groupByUpdatedBy() Group by the updated_by column
 * @method     CgtTelemetryQuery groupByCreatedAt() Group by the created_at column
 * @method     CgtTelemetryQuery groupByUpdatedAt() Group by the updated_at column
 *
 * @method     CgtTelemetryQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     CgtTelemetryQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     CgtTelemetryQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     CgtTelemetry findOne(PropelPDO $con = null) Return the first CgtTelemetry matching the query
 * @method     CgtTelemetry findOneOrCreate(PropelPDO $con = null) Return the first CgtTelemetry matching the query, or a new CgtTelemetry object populated from the query conditions when no match is found
 *
 * @method     CgtTelemetry findOneById(int $id) Return the first CgtTelemetry filtered by the id column
 * @method     CgtTelemetry findOneByName(string $name) Return the first CgtTelemetry filtered by the name column
 * @method     CgtTelemetry findOneBySql(string $sql) Return the first CgtTelemetry filtered by the sql column
 * @method     CgtTelemetry findOneByActive(boolean $active) Return the first CgtTelemetry filtered by the active column
 * @method     CgtTelemetry findOneByCreatedBy(string $created_by) Return the first CgtTelemetry filtered by the created_by column
 * @method     CgtTelemetry findOneByUpdatedBy(string $updated_by) Return the first CgtTelemetry filtered by the updated_by column
 * @method     CgtTelemetry findOneByCreatedAt(string $created_at) Return the first CgtTelemetry filtered by the created_at column
 * @method     CgtTelemetry findOneByUpdatedAt(string $updated_at) Return the first CgtTelemetry filtered by the updated_at column
 *
 * @method     array findById(int $id) Return CgtTelemetry objects filtered by the id column
 * @method     array findByName(string $name) Return CgtTelemetry objects filtered by the name column
 * @method     array findBySql(string $sql) Return CgtTelemetry objects filtered by the sql column
 * @method     array findByActive(boolean $active) Return CgtTelemetry objects filtered by the active column
 * @method     array findByCreatedBy(string $created_by) Return CgtTelemetry objects filtered by the created_by column
 * @method     array findByUpdatedBy(string $updated_by) Return CgtTelemetry objects filtered by the updated_by column
 * @method     array findByCreatedAt(string $created_at) Return CgtTelemetry objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return CgtTelemetry objects filtered by the updated_at column
 *
 * @package    propel.generator.plugins.cgtTelemetryPlugin.lib.model.om
 */
abstract class BaseCgtTelemetryQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseCgtTelemetryQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'CgtTelemetry', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new CgtTelemetryQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    CgtTelemetryQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof CgtTelemetryQuery) {
			return $criteria;
		}
		$query = new CgtTelemetryQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    CgtTelemetry|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = CgtTelemetryPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(CgtTelemetryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    CgtTelemetry A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT ID, NAME, SQL, ACTIVE, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT FROM cgt_telemetryview WHERE ID = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new CgtTelemetry();
			$obj->hydrate($row);
			CgtTelemetryPeer::addInstanceToPool($obj, (string) $row[0]);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    CgtTelemetry|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(CgtTelemetryPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(CgtTelemetryPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(CgtTelemetryPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query on the name column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
	 * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $name The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByName($name = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($name)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $name)) {
				$name = str_replace('*', '%', $name);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::NAME, $name, $comparison);
	}

	/**
	 * Filter the query on the sql column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterBySql('fooValue');   // WHERE sql = 'fooValue'
	 * $query->filterBySql('%fooValue%'); // WHERE sql LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $sql The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterBySql($sql = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($sql)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $sql)) {
				$sql = str_replace('*', '%', $sql);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::SQL, $sql, $comparison);
	}

	/**
	 * Filter the query on the active column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByActive(true); // WHERE active = true
	 * $query->filterByActive('yes'); // WHERE active = true
	 * </code>
	 *
	 * @param     boolean|string $active The value to use as filter.
	 *              Non-boolean arguments are converted using the following rules:
	 *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
	 *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
	 *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByActive($active = null, $comparison = null)
	{
		if (is_string($active)) {
			$active = in_array(strtolower($active), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
		}
		return $this->addUsingAlias(CgtTelemetryPeer::ACTIVE, $active, $comparison);
	}

	/**
	 * Filter the query on the created_by column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByCreatedBy('fooValue');   // WHERE created_by = 'fooValue'
	 * $query->filterByCreatedBy('%fooValue%'); // WHERE created_by LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $createdBy The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByCreatedBy($createdBy = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($createdBy)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $createdBy)) {
				$createdBy = str_replace('*', '%', $createdBy);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::CREATED_BY, $createdBy, $comparison);
	}

	/**
	 * Filter the query on the updated_by column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUpdatedBy('fooValue');   // WHERE updated_by = 'fooValue'
	 * $query->filterByUpdatedBy('%fooValue%'); // WHERE updated_by LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $updatedBy The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByUpdatedBy($updatedBy = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($updatedBy)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $updatedBy)) {
				$updatedBy = str_replace('*', '%', $updatedBy);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::UPDATED_BY, $updatedBy, $comparison);
	}

	/**
	 * Filter the query on the created_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
	 * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $createdAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByCreatedAt($createdAt = null, $comparison = null)
	{
		if (is_array($createdAt)) {
			$useMinMax = false;
			if (isset($createdAt['min'])) {
				$this->addUsingAlias(CgtTelemetryPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($createdAt['max'])) {
				$this->addUsingAlias(CgtTelemetryPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::CREATED_AT, $createdAt, $comparison);
	}

	/**
	 * Filter the query on the updated_at column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
	 * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
	 * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $updatedAt The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function filterByUpdatedAt($updatedAt = null, $comparison = null)
	{
		if (is_array($updatedAt)) {
			$useMinMax = false;
			if (isset($updatedAt['min'])) {
				$this->addUsingAlias(CgtTelemetryPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($updatedAt['max'])) {
				$this->addUsingAlias(CgtTelemetryPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(CgtTelemetryPeer::UPDATED_AT, $updatedAt, $comparison);
	}

	/**
	 * Exclude object from result
	 *
	 * @param     CgtTelemetry $cgtTelemetry Object to remove from the list of results
	 *
	 * @return    CgtTelemetryQuery The current query, for fluid interface
	 */
	public function prune($cgtTelemetry = null)
	{
		if ($cgtTelemetry) {
			$this->addUsingAlias(CgtTelemetryPeer::ID, $cgtTelemetry->getId(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseCgtTelemetryQuery