<?php



/**
 * Skeleton subclass for performing query and update operations on the 'cgt_telemetryview' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Tue Jun 14 08:32:58 2016
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cgtTelemetryPlugin.lib.model
 */
class CgtTelemetryQuery extends BaseCgtTelemetryQuery {

} // CgtTelemetryQuery
